import type { DashboardMockData, ToneStyle, Tone } from "./types";

export const toneStyles: Record<Tone, ToneStyle> = {
  indigo: { iconWrap: "bg-indigo-50", icon: "text-indigo-600" },
  blue: { iconWrap: "bg-sky-50", icon: "text-sky-600" },
  emerald: { iconWrap: "bg-emerald-50", icon: "text-emerald-600" },
  amber: { iconWrap: "bg-amber-50", icon: "text-amber-600" },
};

import { UserRow } from "../../../components/SuperAdminDashboardCom/SADashboardCom/modals/TotalLicensedUsersModal";
import { SubscriptionRow } from "../../../components/SuperAdminDashboardCom/SADashboardCom/modals/ActiveSubscriptionsModal";
import { RevenueRow } from "../../../components/SuperAdminDashboardCom/SADashboardCom/modals/AnnualRevenueAnalyticsModal";

const mockLicensedUsers: UserRow[] = [
  { name: "John Smith", email: "john@example.com", date: "Feb 15, 2026", status: "Active" },
  { name: "Sarah Johnson", email: "sarah@example.com", date: "Feb 14, 2026", status: "Active" },
  { name: "Michael Brown", email: "michael@example.com", date: "Feb 13, 2026", status: "Active" },
  { name: "Emily Davis", email: "emily@example.com", date: "Feb 12, 2026", status: "Active" },
  { name: "David Wilson", email: "david@example.com", date: "Feb 11, 2026", status: "Inactive" },
];

const mockSubscriptions: SubscriptionRow[] = [
  { plan: "Pro Plan - Acme Corp", email: "billing@acme.com", price: "$299/mo", status: "Active" },
  { plan: "Enterprise - TechCo", email: "finance@techco.com", price: "$999/mo", status: "Active" },
  { plan: "Pro Plan - StartupXYZ", email: "admin@startupxyz.com", price: "$299/mo", status: "Active" },
  { plan: "Business - GlobalInc", email: "billing@globalinc.com", price: "$599/mo", status: "Active" },
];

const mockAnnualRevenue: RevenueRow[] = [
  { label: "Pro Plan Revenue", value: "$45,600" },
  { label: "Enterprise Revenue", value: "$89,400" },
  { label: "Business Plan Revenue", value: "$23,800" },
];

export const dashboardMock: DashboardMockData = {
  metricsByRange: {
    "Month to Date (MTD)": {
      licensedUsersCount: "8,547",
      licensedUsersChange: "+12.5%",
      registeredAccountsCount: "12,834",
      registeredAccountsChange: "+8.2%",
      activeSubscriptionsCount: "1,247",
      activeSubscriptionsChange: "+5.4%",
      monthlyRevenue: "$158,800",
      monthlyRevenueChange: "+18.7%",
      annualRevenueCount: "$1.8M",
      annualRevenueChange: "+24.3%",
      newSignups: "342",
      newSignupsChange: "+15.3%",
      churnedAccounts: "28",
      churnedAccountsChange: "-5.2%",
      netGrowth: "+314",
      netGrowthChange: "+22.1%",
      activeBrokers: 147,
      suspendedBrokers: 3,
      activeReferrers: 2845,
      referrersWithLeads: 1923,
      totalCommission: "$847,250",
      marketPaid: "$742,100",
      pendingCommission: "$105,150",
      licensedUsers: mockLicensedUsers,
      registeredAccounts: mockLicensedUsers,
      subscriptions: mockSubscriptions,
      annualRevenue: mockAnnualRevenue,
    },
    "Year to Date (YTD)": {
      licensedUsersCount: "11,200",
      licensedUsersChange: "+22.5%",
      registeredAccountsCount: "18,400",
      registeredAccountsChange: "+18.2%",
      activeSubscriptionsCount: "2,050",
      activeSubscriptionsChange: "+15.4%",
      monthlyRevenue: "$258,800",
      monthlyRevenueChange: "+28.7%",
      annualRevenueCount: "$2.5M",
      annualRevenueChange: "+34.3%",
      newSignups: "850",
      newSignupsChange: "+25.3%",
      churnedAccounts: "45",
      churnedAccountsChange: "-8.2%",
      netGrowth: "+805",
      netGrowthChange: "+32.1%",
      activeBrokers: 210,
      suspendedBrokers: 5,
      activeReferrers: 3450,
      referrersWithLeads: 2500,
      totalCommission: "$1,250,500",
      marketPaid: "$1,100,200",
      pendingCommission: "$150,300",
      licensedUsers: mockLicensedUsers,
      registeredAccounts: mockLicensedUsers,
      subscriptions: mockSubscriptions,
      annualRevenue: mockAnnualRevenue,
    },
    "Last 6 Months": {
      licensedUsersCount: "25,400",
      licensedUsersChange: "+42.5%",
      registeredAccountsCount: "35,200",
      registeredAccountsChange: "+38.2%",
      activeSubscriptionsCount: "4,500",
      activeSubscriptionsChange: "+25.4%",
      monthlyRevenue: "$458,800",
      monthlyRevenueChange: "+48.7%",
      annualRevenueCount: "$4.8M",
      annualRevenueChange: "+54.3%",
      newSignups: "2,450",
      newSignupsChange: "+45.3%",
      churnedAccounts: "120",
      churnedAccountsChange: "-12.2%",
      netGrowth: "+2,330",
      netGrowthChange: "+52.1%",
      activeBrokers: 350,
      suspendedBrokers: 12,
      activeReferrers: 5200,
      referrersWithLeads: 4100,
      totalCommission: "$2,847,250",
      marketPaid: "$2,542,100",
      pendingCommission: "$305,150",
      licensedUsers: mockLicensedUsers,
      registeredAccounts: mockLicensedUsers,
      subscriptions: mockSubscriptions,
      annualRevenue: mockAnnualRevenue,
    },
    "Custom Range": {
      licensedUsersCount: "5,400",
      licensedUsersChange: "+2.5%",
      registeredAccountsCount: "8,200",
      registeredAccountsChange: "+3.2%",
      activeSubscriptionsCount: "800",
      activeSubscriptionsChange: "+1.4%",
      monthlyRevenue: "$88,800",
      monthlyRevenueChange: "+8.7%",
      annualRevenueCount: "$900K",
      annualRevenueChange: "+14.3%",
      newSignups: "150",
      newSignupsChange: "+5.3%",
      churnedAccounts: "15",
      churnedAccountsChange: "-2.2%",
      netGrowth: "+135",
      netGrowthChange: "+12.1%",
      activeBrokers: 95,
      suspendedBrokers: 2,
      activeReferrers: 1500,
      referrersWithLeads: 800,
      totalCommission: "$447,250",
      marketPaid: "$342,100",
      pendingCommission: "$105,150",
      licensedUsers: mockLicensedUsers,
      registeredAccounts: mockLicensedUsers,
      subscriptions: mockSubscriptions,
      annualRevenue: mockAnnualRevenue,
    },
  },

  ranges: [
    "Month to Date (MTD)",
    "Year to Date (YTD)",
    "Last 6 Months",
    "Custom Range",
  ],

  systemHealth: [
    { label: "CRM Sync Status", status: "healthy" },
    { label: "Payment Gateway Status", status: "healthy" },
    { label: "Email Delivery Service", status: "warning" },
    { label: "API Performance", status: "healthy" },
    { label: "Background Job Queue", status: "healthy" },
  ],
};
