import type {
  CurrentPlanSummary,
  InvoiceDetails,
  InvoiceRow,
  PaymentMethod,
  PlanConfig,
  PricingPlan,
  SeatUsageSummary,
} from "./types";

export const planConfigsMock: Record<string, PlanConfig> = {
  starter: {
    id: "starter",
    name: "Starter",
    activeDealsLimit: 25,
    referralPartnersLimit: 5,
    brokerSeatsIncluded: 1,
    monthlyPrice: 49,
    yearlyPrice: 490,
    priceSuffixMonthly: "/month",
    priceSuffixYearly: "/year",
    features: [
      { id: "starter-f1", label: "Up to 25 active deals" },
      { id: "starter-f2", label: "5 referral partners" },
      { id: "starter-f3", label: "Basic automated calculations" },
      { id: "starter-f4", label: "Email notifications" },
      { id: "starter-f5", label: "Basic reporting" },
      { id: "starter-f6", label: "1 broker seat included" },
    ],
  },
  professional: {
    id: "professional",
    name: "Professional",
    activeDealsLimit: 100,
    referralPartnersLimit: "Unlimited",
    brokerSeatsIncluded: 5,
    monthlyPrice: 149,
    yearlyPrice: 1490,
    priceSuffixMonthly: "/month",
    priceSuffixYearly: "/year",
    features: [
      { id: "pro-f1", label: "Up to 100 active deals" },
      { id: "pro-f2", label: "Unlimited referral partners" },
      { id: "pro-f3", label: "Automated commission calculations" },
      { id: "pro-f4", label: "Email & SMS notifications" },
      { id: "pro-f5", label: "Advanced reporting & exports" },
      { id: "pro-f6", label: "Up to 5 broker seats included" },
    ],
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    activeDealsLimit: "Unlimited",
    referralPartnersLimit: "Unlimited",
    brokerSeatsIncluded: "Unlimited",
    monthlyPrice: null,
    yearlyPrice: null,
    priceSuffixMonthly: "",
    priceSuffixYearly: "",
    features: [
      { id: "ent-f1", label: "Unlimited deals" },
      { id: "ent-f2", label: "Unlimited referral partners" },
      { id: "ent-f3", label: "Unlimited broker seats" },
      { id: "ent-f4", label: "Custom integrations" },
      { id: "ent-f5", label: "White-label options" },
      { id: "ent-f6", label: "Dedicated account manager" },
      { id: "ent-f7", label: "24/7 premium support" },
    ],
  },
};

export const currentPlanMock: CurrentPlanSummary = {
  planId: "professional",
  planName: "Professional",
  price: 149,
  priceSuffix: "/month",
  features: planConfigsMock.professional.features,
  nextBillingDate: "Jan 01, 2026",
  billingCycle: "monthly",
  billingCycleLabel: "Monthly",
  activeDealsLimit: 100,
  referralPartnersLimit: "Unlimited",
  brokerSeatsIncluded: 5,
};

export const seatUsageMock: SeatUsageSummary = {
  usedSeats: 3,
  totalSeats: 5,
  additionalSeatMonthlyCost: 29,
};

export const paymentMethodsMock: PaymentMethod[] = [
  {
    id: "pm-1",
    type: "card",
    label: "Visa ending in 4242",
    subLabel: "Expires 12/28",
    isDefault: true,
  },
  {
    id: "pm-2",
    type: "bank",
    label: "Bank Direct Debit",
    subLabel: "BSB: ••• ••• • Account: ••• 5678",
    isDefault: false,
  },
];

export const invoicesMock: InvoiceRow[] = [
  {
    id: "inv-9201",
    invoiceDate: "Dec 01, 2025",
    planName: "Professional Plan",
    invoiceRef: "INV-9201",
    amount: 149,
    status: "Paid",
  },
  {
    id: "inv-9200",
    invoiceDate: "Nov 01, 2025",
    planName: "Professional Plan",
    invoiceRef: "INV-9200",
    amount: 149,
    status: "Paid",
  },
  {
    id: "inv-9199",
    invoiceDate: "Oct 01, 2025",
    planName: "Professional Plan",
    invoiceRef: "INV-9199",
    amount: 149,
    status: "Paid",
  },
  {
    id: "inv-9198",
    invoiceDate: "Sep 01, 2025",
    planName: "Professional Plan",
    invoiceRef: "INV-9198",
    amount: 149,
    status: "Paid",
  },
  {
    id: "inv-9197",
    invoiceDate: "Aug 01, 2025",
    planName: "Professional Plan",
    invoiceRef: "INV-9197",
    amount: 149,
    status: "Paid",
  },
];

export const pricingPlansMock: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Perfect for individual brokers",
    monthly: {
      amount: 49,
      label: "$49",
      suffix: "/month",
    },
    yearly: {
      amount: 490,
      label: "$490",
      suffix: "/year",
    },
    features: [
      "Up to 25 active deals",
      "5 referral partners",
      "$5 per additional referral partner",
      "Automated calculations",
      "Email notifications",
      "Basic reporting",
      "1 broker seat included",
    ],
    ctaLabel: "Choose Starter",
  },
  {
    id: "professional",
    name: "Professional",
    tagline: "For growing brokerages",
    monthly: {
      amount: 149,
      label: "$149",
      suffix: "/month",
    },
    yearly: {
      amount: 1490,
      label: "$1,490",
      suffix: "/year",
    },
    features: [
      "Up to 100 active deals",
      "Unlimited referral partners",
      "Advanced automation",
      "Email & SMS notifications",
      "Advanced reporting & exports",
      "Priority support",
      "Up to 5 broker seats included",
    ],
    ctaLabel: "Choose Professional",
    isPopular: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "For large organizations",
    monthly: {
      amount: null,
      label: "Custom",
    },
    yearly: {
      amount: null,
      label: "Custom",
    },
    features: [
      "Contact sales",
      "Unlimited deals",
      "Unlimited users",
      "Custom integrations",
      "White-label options",
      "Dedicated account manager",
      "24/7 premium support",
    ],
    ctaLabel: "Contact Sales",
  },
];

export const invoiceDetailsMock: InvoiceDetails = {
  invoiceId: "INV-9201",
  issueDate: "Dec 01, 2025",
  status: "Paid",
  fromName: "ReferNow",
  fromDepartment: "Billing Department",
  fromEmail: "support@refernow.com",
  billToName: "PrimeEstates",
  billToContact: "Tom Harris",
  billToEmail: "tom@primeestates.com",
  items: [
    {
      id: "line-1",
      description: "Professional Plan (Monthly)",
      quantity: 1,
      unitPrice: 149,
      amount: 149,
    },
    {
      id: "line-2",
      description: "Additional Broker Seat",
      quantity: 1,
      unitPrice: 29,
      amount: 29,
    },
  ],
  subtotal: 178,
  taxLabel: "Tax (GST 10%)",
  taxAmount: 17.8,
  totalPaid: 195.8,
  paymentMethodLabel: "Payment Method",
  paymentMethodValue: "Visa ending 4242",
  paidOnLabel: "Paid on",
  paidOnValue: "Dec 01, 2025",
  footerNote:
    "Thank you for your business. For questions about this invoice, contact support@refernow.com",
};
