import type { ReferralRow } from "./types";

export const referralRows: ReferralRow[] = [
  {
    id: 1,
    borrowerName: "Sarah Mitchell",
    referrer: "ABC Realty Group",
    loanAmount: 450000,
    pipelineStage: "Submitted to Lender",
    expectedCommission: 4500,
    commissionStatus: "Pending",
    dateSubmitted: "Mar 1, 2026",
    assignedTeamMember: "John Broker",
    settlementDate: "Apr 12, 2026",
  },
  {
    id: 2,
    borrowerName: "James Rodriguez",
    referrer: "Elite Financial Partners",
    loanAmount: 780000,
    pipelineStage: "Approved",
    expectedCommission: 7800,
    commissionStatus: "Approved",
    dateSubmitted: "Feb 28, 2026",
    assignedTeamMember: "Sarah Smith",
    settlementDate: "Mar 29, 2026",
  },
  {
    id: 3,
    borrowerName: "Emily Chen",
    referrer: "ABC Realty Group",
    loanAmount: 325000,
    pipelineStage: "Application Started",
    expectedCommission: 3250,
    commissionStatus: "Pending",
    dateSubmitted: "Mar 5, 2026",
    assignedTeamMember: "Mike Johnson",
    settlementDate: "Apr 15, 2026",
  },
  {
    id: 4,
    borrowerName: "Michael Thompson",
    referrer: "Premier Mortgage Solutions",
    loanAmount: 590000,
    pipelineStage: "Funded",
    expectedCommission: 5900,
    commissionStatus: "Paid",
    dateSubmitted: "Feb 15, 2026",
    assignedTeamMember: "John Broker",
    settlementDate: "Feb 28, 2026",
  },
  {
    id: 5,
    borrowerName: "Lisa Anderson",
    referrer: "Elite Financial Partners",
    loanAmount: 410000,
    pipelineStage: "Contacted",
    expectedCommission: 4100,
    commissionStatus: "Pending",
    dateSubmitted: "Mar 7, 2026",
    assignedTeamMember: "Sarah Smith",
    settlementDate: "Apr 9, 2026",
  },
  {
    id: 6,
    borrowerName: "David Park",
    referrer: "Summit Property Advisors",
    loanAmount: 875000,
    pipelineStage: "New Referral",
    expectedCommission: 8750,
    commissionStatus: "Pending",
    dateSubmitted: "Mar 8, 2026",
    assignedTeamMember: "Mike Johnson",
    settlementDate: "Apr 22, 2026",
  },
  {
    id: 7,
    borrowerName: "Jennifer Williams",
    referrer: "ABC Realty Group",
    loanAmount: 520000,
    pipelineStage: "Approved",
    expectedCommission: 5200,
    commissionStatus: "Scheduled",
    dateSubmitted: "Feb 20, 2026",
    assignedTeamMember: "John Broker",
    settlementDate: "Mar 18, 2026",
  },
  {
    id: 8,
    borrowerName: "Robert Martinez",
    referrer: "Premier Mortgage Solutions",
    loanAmount: 395000,
    pipelineStage: "Submitted to Lender",
    expectedCommission: 3950,
    commissionStatus: "Pending",
    dateSubmitted: "Mar 3, 2026",
    assignedTeamMember: "Sarah Smith",
    settlementDate: "Apr 10, 2026",
  },
];
